### ISSUE TITLE
Issues template

### ISSUE THREAD

**Issue by strypey** [TheAssassin/fetcher#3]
How do we modify (remove?) the Issues template for this GH repo?

**Comment by TheAssassin** [comment]
GitHub manages this kind of stuff in a subdirectory called `.github`. Check out https://github.com/TheAssassin/fetcher/tree/master/.github.

**Comment by strypey** [comment]
Sweet as. For now, I've changed all instances of "Etcher" in the template to "Fetcher". Are you happy with that template from a dev POV, or are there other changes that you'd like to make?

**Comment by TheAssassin** [comment]
Seems good enough to me. I personally don't use issue templates in my projects.

**Comment by strypey** [comment]
Sweet as. I've closed this.
